[project]
dot_env = ".env"

[networks.contracts]
price_feed = {force_deploy = false, deployer_script = "deploy_mocks.py"}

[networks.sepolia]
chain_id = 11155111
default_account_name = "sepolia_1"
explorer_type = "blockscout"
explorer_uri = "https://eth-sepolia.blockscout.com/"
save_to_db = false
url = "$SEPOLIA_RPC_URL"

[networks.anvil]
chain_id = 31337
default_account_name = "anvil1"
prompt_live = false
save_to_db = false
unsafe_password_file = "$ANVIL1_PASSWORD_FILE"
url = "http://127.0.0.1:8545"

[networks.zksync-local]
chain_id = 260
is_zksync = true
prompt_live = false
save_to_db = true
url = "http://127.0.0.1:8011"

[networks.sepolia.contracts]
price_feed = {address = "0x694AA1769357215DE4FAC081bf1f309aDC325306"}

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
